### ISSUE TITLE
Configuración DigitalOcean

### ISSUE THREAD

**Issue by yodra** [fullstacktf/fs5-recomendador-backend#1]
- [x] Crear un droplet
- [x] Instalar docker
- [x] Configuración Cloudflare para HTTPS y gestionar DNS
- [x] Configuración Nginx/Apache como servidor

**Comment by japmelian** [comment]
El Droplet está creado y configurado para trabajar con Nginx.
La URL del proyecto es [https://urecommend.me/](https://urecommend.me/)

Faltaría únicamente la instalación de Docker, que me encargo yo.
